# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q6hDNwKFkQZBroo7z8V3gQXz2VbQPSlR
"""

config = {
    'train_dataset': 'path/train.csv',
    'val_dataset': 'path/val.csv',
    'test_dataset': 'path/test.csv',
    'seg_batch_size': 1,
    'reg_batch_size': 16,
    'val_batch_size': 1,
    'runs': '/path_runs/',
}


model_params = {
    'epochs_seg': 150,
    'epochs_reg': 1500,
    'lambda': 100,
    'learning_rate': 0.001,
    'betas': [0.9, 0.999],
    'epoch_save': 10,
    'epoch_save_reg': 50,
}

seg_params = {
    'train_path': train_path,
    'val_path': val_path,
    'path': path,
    'batch_size': 1,
    'num_epochs': 60,
    'best_loss_path': best_loss_path,
    'seg_model_path': seg_model_path
}

reg_params = {
    'train_path': train_path,
    'val_path': val_path,
    'path': path,
    'train_batch_size': 16,
    'val_batch_size': 1,
    'num_epochs': 400,
    'lambda_value': 100,
    'reg_model_path': reg_model_path,
    'runs': runs
}

regseg_params = {
    'train_path': train_path,
    'val_path': val_path,
    'path': path,
    'train_batch_size': 8,
    'val_batch_size': 1,
    'num_epochs': 400,
    'lambda_value': 100,
    'regseg_model_path': regseg_model_path,
    'runs': runs
}