# -*- coding: utf-8 -*-
"""transforms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hy3kTTbjRNeYbXVC-u9MxLYjrTBMxMwM
"""

import torch
import torchio as tio

# Transforms 1
transform_1 = tio.Compose([                             
    tio.RandomAnisotropy(downsampling=(1.5,3), p=0.05),
    tio.RandomSwap((1,1,1), p=0.1),      
    tio.RandomNoise(std=(0,0.2), p=0.05),          
    tio.OneOf({                       
        tio.RandomAffine(): 3,            
        tio.RandomElasticDeformation(): 0.1,  
    }, p=0.2), 
    tio.RandomBiasField(coefficients=(0.1,0.2), p=0.05),
    tio.RescaleIntensity(out_min_max=(0,1)),                               
])


# Transforms 2
transform_2 = tio.Compose([                             
    tio.RandomBiasField(coefficients=(0.1,0.4), p=0.2),
    tio.RandomMotion(degrees=(5,15), translation=(5,15), num_transforms=3, p=0.2),      
    tio.RandomSpike(num_spikes=(1,3), intensity=(0.1, 0.4), p=0.2),          
    tio.RandomGhosting(num_ghosts=(3,12), intensity=(0.05, 0.55), p=0.2),  
    tio.RescaleIntensity(out_min_max=(0,1)),                               
])


# Transforms 3
transform_3 = tio.Compose([           
    tio.RandomAnisotropy(downsampling=(1.5,2.5), p=0.2),                      
    tio.RandomSwap((1,1,1), 1000, p=0.2),
    tio.RandomBlur(std=(0,0.3), p=0.2),                 
    tio.RandomNoise(std=(0,0.25), p=0.15),         
    tio.OneOf({                       
        tio.RandomAffine(scales=(0.05,0.2), degrees=(5,20), translation=(0,5)): 0.7,            
        tio.RandomElasticDeformation(): 0.3,  
    }, p=0.4),      
    tio.RandomGamma(log_gamma=(-0.3, 0.3),p=0.3),                    
    tio.RescaleIntensity(out_min_max=(0,1)),   
])



# Transforms 4
transform_4 = tio.Compose([     
    tio.RandomFlip(0,p=0.2),
    tio.RandomFlip(1,p=0.2),
    tio.RandomFlip(2,p=0.2),                  
    tio.RandomNoise(std=(0,0.45), p=0.4),         
    tio.RescaleIntensity(out_min_max=(0,1)),   
])


# Transforms 5
transform_5 = tio.Compose([    
    tio.RandomFlip(p=0.3),
    tio.RandomAffine(scales=(0,0.1), degrees=(20), translation=(0,15),p=0.6),            
    tio.RandomElasticDeformation(p=0.4),
    tio.RescaleIntensity(out_min_max=(0,1)),   
])


# Transforms 6
transform_6 = tio.Compose([   
    tio.RandomFlip(0,p=0.1),
    tio.RandomFlip(1,p=0.1),
    tio.RandomFlip(2,p=0.1),      
    tio.RandomAnisotropy(downsampling=(1.5,3), p=0.1),                      
    tio.RandomSwap((1,1,1), 3000, p=0.1),
    tio.RandomGamma(log_gamma=(-0.2, 0.2),p=0.1),   
    tio.RandomBlur(std=(0,0.2), p=0.1),                 
    tio.RandomNoise(std=(0,0.35), p=0.1),         
    tio.OneOf({                       
        tio.RandomAffine(scales=(0.05,0.25), degrees=(5,20), translation=(0,5)): 0.65,            
        tio.RandomElasticDeformation(): 0.35,  
    }, p=0.1),  
    tio.OneOf({                
        tio.RandomBiasField(coefficients=(0.1,0.35), p=0.1),
        tio.RandomMotion(degrees=(0,10), translation=(0,10), num_transforms=4, p=0.1),      
        tio.RandomSpike(num_spikes=(1,3), intensity=(0.1, 0.4), p=0.1),          
        tio.RandomGhosting(num_ghosts=(3,12), intensity=(0.05, 0.55), p=0.1),  
    },p=0.4),
    tio.RescaleIntensity(out_min_max=(0,1)),   
])


# Transforms 7
transform_7 = tio.Compose([
    tio.OneOf({                       
        tio.RandomAffine(),            
        tio.RandomElasticDeformation(), 
        tio.RandomFlip(0),
        tio.RandomFlip(1),
        tio.RandomFlip(2),      
        tio.RandomAnisotropy(),                      
        tio.RandomSwap((1,1,1), 1000),
        tio.RandomGamma(log_gamma=(-0.2, 0.2)),   
        tio.RandomBlur(std=(0,0.2)),                 
        tio.RandomNoise(std=(0,0.25)),  
        tio.RandomBiasField(coefficients=(0.1,0.25)),
        tio.RandomMotion(),      
        tio.RandomSpike(intensity=(0.1, 0.3)),          
        tio.RandomGhosting(),  
    }, p=0.5),  
    tio.RescaleIntensity(out_min_max=(0,1)),   
])



# Validation transform
transform_val = tio.Compose([
    tio.RescaleIntensity(out_min_max=(0,1)), 
                             
])


transforms_dict = {
    't_1': transform_1,
    't_2': transform_2,
    't_3': transform_3,
    't_4': transform_4,
    't_5': transform_5,
    't_6': transform_6,
    't_7': transform_7,
    'val': transform_val
    }